<a href="https://colab.research.google.com/github/Ibreez16/pandas_learning/blob/main/Pandas_Practice_(3_5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [ ]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,13,1,6,8,5,10,4,6,6,19,74,15,141,95,18,11,1,0,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,14,4,8,7,7,20,8,3,2,7,106,15,164,114,23,12,0,0,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,7,2,5,5,2,13,1,3,7,16,75,10,150,97,14,8,2,0,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,21,9,9,13,8,13,6,8,9,9,163,28,249,172,40,24,4,0,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,10,5,3,7,3,15,7,5,4,12,69,9,179,107,14,9,3,0,19,4,516,419,24,3,5,28,4,0

In [ ]:
team_list = df["Team"].unique()

In [ ]:
result_dict = {}
for i in team_list:
  new_df = df[df["Team"] == i]
  total_attempts_sum = new_df['Total Attempts'].sum()
  total_on_target_sum = new_df['On Target'].sum()
  percentage = ((total_on_target_sum / total_attempts_sum) * 100).round(2)
  result_dict[i] = float(percentage)

result_dict = pd.Series(result_dict)
sorted_series = result_dict.sort_values(ascending = False)
sorted_dict = sorted_series.to_dict()
sorted_dict

{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.15,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'France': 34.65,
 'Germany': 34.33,
 'Croatia': 33.73,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.33,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [ ]:
# code here

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [ ]:
teams_played

                Counts  rank
Team
France               7   1.0
Argentina            7   2.0
Croatia              7   3.0
Morocco              7   4.0
Brazil               5   5.0
Portugal             5   6.0
England              5   7.0
Netherlands          5   8.0
Spain                4   9.0
Japan                4  10.0
Switzerland          4  11.0
Korea Republic       4  12.0
Australia            4  13.0
Poland               4  14.0
Senegal              4  15.0
United States        4  16.0
Mexico               3  17.0
Saudi Arabia         3  18.0
Denmark              3  19.0
Tunisia              3  20.0
Iran                 3  21.0
Ecuador              3  22.0
Qatar                3  23.0
Wales                3  24.0
Canada               3  25.0
Belgium              3  26.0
Costa Rica           3  27.0
Germany              3  28.0
Uruguay              3  29.0
Cameroon             3  30.0
Ghana                3  31.0
Serbia               3  32.0

In [ ]:
# code here
teams_played = df["Team"].value_counts().reset_index()
teams_played.columns = ["Team", "Counts"]
teams_played['rank'] = teams_played["Counts"].rank(method='first', ascending=False)
teams_played.set_index("Team", inplace=True)

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [ ]:
# code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

In [ ]:
df.describe()

,Sl. No,Match No.,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,32.500000,1.343750,43.476562,1.203125,0.117188,0.914062,11.257812,4.007812,4.835938,6.914062,4.343750,13.562500,4.671875,4.906250,4.648438,12.234375,92.703125,12.453125,169.281250,109.476562,14.812500,8.265625,1.726562,0.023438,12.320312,1.976562,502.859375,430.929688,19.523438,4.898438,4.468750,14.250000,0.335938,1.429688
std,37.094474,18.545539,1.342448,11.442403,1.324270,0.322907,1.150333,5.406683,2.588576,2.610630,3.998085,2.733397,6.901729,2.886595,3.080131,2.936573,6.176517,29.440547,18.152399,34.120661,30.776298,7.230458,5.101311,1.514834,0.151883,4.691983,1.731891,160.160487,160.893724,8.596799,3.520111,2.774852,4.712189,0.941412,1.389973
min,1.000000,1.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,32.000000,0.000000,56.000000,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,225.000000,156.000000,4.000000,0.000000,0.000000,5.000000,0.000000,0.000000
25%,32.750000,16.750000,0.000000,35.000000,0.000000,0.000000,0.000000,7.750000,2.000000,3.000000,4.000000,3.000000,8.000000,2.000000,3.000000,3.000000,8.000000,72.750000,7.000000,149.500000,87.750000,10.000000,5.000000,1.000000,0.000000,9.000000,1.000000,398.250000,323.250000,13.000000,3.000000,2.000000,11.000000,0.000000,0.000000
50%,64.500000,32.500000,1.000000,45.000000,1.000000,0.000000,1.000000,10.000000,4.000000,4.000000,6.000000,4.000000,12.000000,4.500000,4.000000,4.000000,11.000000,93.000000,9.000000,170.500000,106.000000,15.000000,8.000000,2.000000,0.000000,12.000000,2.000000,495.500000,419.000000,19.000000,4.000000,4.000000,14.000000,0.000000,1.000000
75%,96.250000,48.250000,2.000000,51.000000,2.000000,0.000000,1.000000,14.000000,6.000000,6.000000,9.000000,5.000000,18.000000,7.000000,6.250000,6.000000,16.250000,111.250000,14.000000,188.000000,129.000000,20.000000,11.000000,2.000000,0.000000,15.000000,3.000000,589.500000,519.750000,24.000000,6.000000,6.000000,17.000000,0.000000,3.000000
max,128.000000,64.000000,7.000000,78.000000,7.000000,1.000000,6.000000,32.000000,13.000000,17.000000,24.000000,15.000000,36.000000,13.000000,16.000000,19.000000,29.000000,186.000000,192.000000,259.000000,192.000000,40.000000,27.000000,8.000000,1.000000,30.000000,10.000000,1070.000000,994.000000,53.000000,25.000000,14.000000,30.000000,5.000000,3.000000

In [ ]:
df.isnull().sum()

Sl. No                             0
Match No.                          0
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Red Cards                          0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Pts                                0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#"Sl No", "Match No.", "Red Cards" and "Pts" permanently.
df.drop(columns=["Sl. No", "Match No.", "Red Cards", "Pts"],inplace=True)

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [ ]:
# code here
rank = df["Team"].value_counts().rank(method="first", ascending=False).astype('int16')
df['Rank'] = df["Team"].map(rank)
df.set_index("Rank",inplace=True)
df.sort_index()

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
Rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,France,Argentina,D,3,40,3,0,1,10,5,3,7,3,15,7,5,4,12,69,9,179,107,14,9,3,19,4,516,419,24,3,5,28,4
1,France,Denmark,D,2,44,2,0,2,21,6,8,16,5,15,7,4,1,13,105,11,155,105,16,12,1,4,1,503,437,23,12,6,10,0
1,France,Tunisia,D,0,56,0,0,0,9,3,4,4,5,14,6,5,3,21,101,11,138,99,10,4,0,6,2,636,566,20,5,8,17,0
1,France,Morocco,D,2,34,2,0,0,14,2,8,12,2,9,6,3,2,6,67,8,126,85,12,8,0,11,4,358,307,5,2,2,13,0
1,France,Australia,D,4,56,4,0,4,22,7,9,18,4,30,6,3,8,19,106,26,173,135,32,27,0,5,0,734,672,34,17,8,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,Ghana,Korea Republic,H,3,32,3,0,2,8,3,3,7,1,8,3,4,3,7,56,5,122,66,12,5,2,9,1,319,260,13,4,5,14,0
31,Ghana,Uruguay,H,0,46,0,0,0,9,4,4,4,5,12,5,8,4,12,93,8,188,111,13,5,2,18,2,460,377,20,2,5,12,0
32,Serbia,Cameroon,G,3,49,2,1,3,16,6,8,11,5,20,4,16,5,12,140,11,184,122,22,12,2,13,4,513,433,23,4,3,8,0
32,Serbia,Brazil,G,0,34,0,0,0,4,0,3,1,3,10,3,4,3,7,69,4,140,91,15,6,3,12,0,403,341,13,3,4,8,0
32,Serbia,Switzerland,G,2,45,2,0,1,11,4,6,10,1,17,6,4,4,10,86,7,157,95,10,5,7,18,0,476,390,23,6,2,14,0

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [ ]:
# code here
url1 = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv'
url2 = ' https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv'
df_titanic_1 = pd.read_csv(url1)
df_titanic_2 = pd.read_csv(url2)

In [ ]:
df_titanic_1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df_titanic_1.dropna(subset='Age',inplace=True)
df_titanic_1[df_titanic_1["Age"].isnull()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [ ]:
df_titanic_2

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
df_titanic_2["Age"].fillna(20, inplace=True)
df_titanic_2

/tmp/ipython-input-2260915100.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_titanic_2["Age"].fillna(20, inplace=True)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,20.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,20.0,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,20.0,1,1,2668,22.3583,NaN,C

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

In [2]:
ipl_dataset = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv")
ipl_dataset

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [ ]:
new_df = pd.DataFrame(ipl_dataset["Team1"].unique())
new_df.rename(columns={0: "Teams"}, inplace=True)

match_count = ipl_dataset[['Team1', 'Team2']].stack().value_counts()
new_df["Matches Played"] = new_df["Teams"].map(match_count)

wins = ipl_dataset["WinningTeam"].value_counts()
new_df["Wins"] = new_df["Teams"].map(wins)
new_df["Win%"] = ((new_df["Wins"]/new_df["Matches Played"])*100).round()

home_wins = ipl_dataset[ipl_dataset["Team1"] == ipl_dataset["WinningTeam"]]
home_wins = home_wins["Team1"].value_counts()
new_df["Home Wins"] = new_df['Teams'].map(home_wins)
new_df["Home Wins%"] = ((new_df["Home Wins"]/new_df["Matches Played"])*100).round()

away_wins = ipl_dataset[ipl_dataset["Team2"] == ipl_dataset["WinningTeam"]]
away_wins = away_wins["Team2"].value_counts()
new_df["Away Wins"] = new_df['Teams'].map(away_wins)
new_df["Away Wins%"] = ((new_df["Away Wins"]/new_df["Matches Played"])*100).round()
new_df

,Teams,Matches Played,Wins,Win%,Home Wins,Home Wins%,Away Wins,Away Wins%
0,Rajasthan Royals,192,96,50.0,49,26.0,47,24.0
1,Royal Challengers Bangalore,226,109,48.0,61,27.0,48,21.0
2,Sunrisers Hyderabad,152,75,49.0,36,24.0,39,26.0
3,Delhi Capitals,224,36,16.0,15,7.0,21,9.0
4,Chennai Super Kings,208,121,58.0,65,31.0,56,27.0
5,Gujarat Titans,16,12,75.0,4,25.0,8,50.0
6,Lucknow Super Giants,15,9,60.0,7,47.0,2,13.0
7,Kolkata Knight Riders,223,114,51.0,56,25.0,58,26.0
8,Punjab Kings,218,13,6.0,7,3.0,6,3.0
9,Mumbai Indians,231,131,57.0,65,28.0,66,29.0
10,Rising Pune Supergiant,30,10,33.0,5,17.0,5,17.0
11,Gujarat Lions,30,13,43.0,5,17.0,8,27.0
12,Pune Warriors,46,12,26.0,6,13.0,6,13.0
13,Deccan Chargers,75,29,39.0,13,17.0,16,21.0
14,Kochi Tuskers Kerala,14,6,43.0,3,21.0,3,21.0

In [ ]:
# code here
mapping_dict = {'Delhi Daredevils': 'Delhi Capitals', 'Kings XI Punjab': 'Punjab Kings', 'Rising Pune Supergiants' : 'Rising Pune Supergiant'}
ipl_dataset[['Team1', 'Team2']] = ipl_dataset[['Team1', 'Team2']].replace(mapping_dict)
ipl_dataset

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Capitals,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Punjab Kings,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

###`Q-7:` Venues with most "no result" matches.

In [ ]:
# code here
ipl_dataset["WinningTeam"].value_counts()

WinningTeam
Mumbai Indians                 131
Chennai Super Kings            121
Kolkata Knight Riders          114
Royal Challengers Bangalore    109
Rajasthan Royals                96
Kings XI Punjab                 88
Sunrisers Hyderabad             75
Delhi Daredevils                67
Delhi Capitals                  36
Deccan Chargers                 29
Gujarat Lions                   13
Punjab Kings                    13
Gujarat Titans                  12
Pune Warriors                   12
Rising Pune Supergiant          10
Lucknow Super Giants             9
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [ ]:
# code here

ipl_dataset["All Players"] = (ipl_dataset["Team1Players"] + ipl_dataset['Team2Players'])
no_of_players = ipl_dataset['All Players'].str.replace(r"[\[\]']", "", regex=True).str.split(',').explode().value_counts()
no_of_players

All Players
 MS Dhoni                    233
 KD Karthik                  229
 RA Jadeja                   209
 SK Raina                    204
 KA Pollard                  189
                            ...
 AB DindaJ Arunkumar           1
A Chopra                       1
 PJ SangwanS Vidyut            1
 MM PatelAC Gilchrist          1
 DS KulkarniS Chanderpaul      1
Name: count, Length: 1589, dtype: int64

In [3]:
final_matches = ipl_dataset[ipl_dataset['MatchNumber'] == "Final"]
final_matches["All Players"] = (final_matches["Team1Players"] + final_matches['Team2Players'])
no_of_players_in_final = final_matches['All Players'].str.replace(r"[\[\]']", "", regex=True).str.split(',').explode().value_counts()
no_of_players_in_final

/tmp/ipython-input-1351/1544313360.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_matches["All Players"] = (final_matches["Team1Players"] + final_matches['Team2Players'])

All Players
MS Dhoni         10
SK Raina          8
AT Rayudu         7
DJ Bravo          7
RA Jadeja         7
                 ..
M Kaif            1
SK Warne          1
Sohail Tanvir     1
SK Trivedi        1
MM Patel          1
Name: count, Length: 187, dtype: int64

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

In [29]:
def point_table(season):
  print(season)
  new_df = pd.DataFrame(ipl_dataset[ipl_dataset["Season"] == season])

  result_df = new_df["Team1"].unique()
  result_df = pd.DataFrame(result_df).rename(columns = {0: "Team Name"})

  match_count = new_df[['Team1', 'Team2']].stack().value_counts()
  result_df["Matches Played"] = result_df["Team Name"].map(match_count)

  wins = new_df["WinningTeam"].value_counts()
  result_df["Wins"] = result_df["Team Name"].map(wins)

  result_df["Points"] = result_df["Wins"] * 2

  result_df = result_df.set_index("Team Name")
  result_df.sort_index(inplace=True)
  result_df.sort_values('Points',ascending=False, inplace=True)

  result_df["Ranks"] = result_df["Points"].rank(ascending=False, method='first')

  result_df["Season Position"] = " "

  winner = result_df.head().index[0]
  runner = result_df.head().index[1]
  qualifier = result_df.head().index[2]
  eliminator = result_df.head().index[3]

  result_df.at[winner, 'Season Position'] = str('Winner')
  result_df.at[runner, 'Season Position'] = str('Runner')
  result_df.at[qualifier, 'Season Position'] = str('Losing Team in Qualifier2')
  result_df.at[eliminator, 'Season Position'] = str('Losing Team in Eliminator')

  return result_df


season_parameter = ipl_dataset["Season"].unique()
for i in season_parameter:
  display(point_table(i))

2022

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Gujarat Titans,16,12,24,1.0,Winner
Rajasthan Royals,17,10,20,2.0,Runner
Royal Challengers Bangalore,16,9,18,3.0,Losing Team in Qualifier2
Lucknow Super Giants,15,9,18,4.0,Losing Team in Eliminator
Punjab Kings,14,7,14,5.0,
Delhi Capitals,14,7,14,6.0,
Sunrisers Hyderabad,14,6,12,7.0,
Kolkata Knight Riders,14,6,12,8.0,
Chennai Super Kings,14,4,8,9.0,
Mumbai Indians,14,4,8,10.0,

2021

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Chennai Super Kings,16,11,22,1.0,Winner
Delhi Capitals,16,10,20,2.0,Runner
Kolkata Knight Riders,17,9,18,3.0,Losing Team in Qualifier2
Royal Challengers Bangalore,15,9,18,4.0,Losing Team in Eliminator
Mumbai Indians,14,7,14,5.0,
Punjab Kings,14,6,12,6.0,
Rajasthan Royals,14,5,10,7.0,
Sunrisers Hyderabad,14,3,6,8.0,

2020/21

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Mumbai Indians,16,11,22,1.0,Winner
Delhi Capitals,17,9,18,2.0,Runner
Sunrisers Hyderabad,16,8,16,3.0,Losing Team in Qualifier2
Kolkata Knight Riders,14,7,14,4.0,Losing Team in Eliminator
Royal Challengers Bangalore,15,7,14,5.0,
Chennai Super Kings,14,6,12,6.0,
Kings XI Punjab,14,6,12,7.0,
Rajasthan Royals,14,6,12,8.0,

2019

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Mumbai Indians,16,11,22,1.0,Winner
Chennai Super Kings,17,10,20,2.0,Runner
Delhi Capitals,16,10,20,3.0,Losing Team in Qualifier2
Kings XI Punjab,14,6,12,4.0,Losing Team in Eliminator
Kolkata Knight Riders,14,6,12,5.0,
Sunrisers Hyderabad,15,6,12,6.0,
Rajasthan Royals,14,5,10,7.0,
Royal Challengers Bangalore,14,5,10,8.0,

2018

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Chennai Super Kings,16,11,22,1.0,Winner
Sunrisers Hyderabad,17,10,20,2.0,Runner
Kolkata Knight Riders,16,9,18,3.0,Losing Team in Qualifier2
Rajasthan Royals,15,7,14,4.0,Losing Team in Eliminator
Mumbai Indians,14,6,12,5.0,
Kings XI Punjab,14,6,12,6.0,
Royal Challengers Bangalore,14,6,12,7.0,
Delhi Daredevils,14,5,10,8.0,

2017

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Mumbai Indians,17,12,24,1.0,Winner
Rising Pune Supergiant,16,10,20,2.0,Runner
Kolkata Knight Riders,16,9,18,3.0,Losing Team in Qualifier2
Sunrisers Hyderabad,14,8,16,4.0,Losing Team in Eliminator
Kings XI Punjab,14,7,14,5.0,
Delhi Daredevils,14,6,12,6.0,
Gujarat Lions,14,4,8,7.0,
Royal Challengers Bangalore,13,3,6,8.0,

2016

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Sunrisers Hyderabad,17,11,22,1.0,Winner
Gujarat Lions,16,9,18,2.0,Runner
Royal Challengers Bangalore,16,9,18,3.0,Losing Team in Qualifier2
Kolkata Knight Riders,15,8,16,4.0,Losing Team in Eliminator
Mumbai Indians,14,7,14,5.0,
Delhi Daredevils,14,7,14,6.0,
Rising Pune Supergiants,14,5,10,7.0,
Kings XI Punjab,14,4,8,8.0,

2015

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Chennai Super Kings,17,10,20,1.0,Winner
Mumbai Indians,16,10,20,2.0,Runner
Royal Challengers Bangalore,16,8,16,3.0,Losing Team in Qualifier2
Kolkata Knight Riders,13,7,14,4.0,Losing Team in Eliminator
Rajasthan Royals,14,7,14,5.0,
Sunrisers Hyderabad,14,7,14,6.0,
Delhi Daredevils,14,5,10,7.0,
Kings XI Punjab,14,3,6,8.0,

2014

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Kings XI Punjab,17,12,24,1.0,Winner
Kolkata Knight Riders,16,11,22,2.0,Runner
Chennai Super Kings,16,10,20,3.0,Losing Team in Qualifier2
Mumbai Indians,15,7,14,4.0,Losing Team in Eliminator
Rajasthan Royals,14,7,14,5.0,
Sunrisers Hyderabad,14,6,12,6.0,
Royal Challengers Bangalore,14,5,10,7.0,
Delhi Daredevils,14,2,4,8.0,

2013

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Mumbai Indians,19,13,26,1.0,Winner
Chennai Super Kings,18,12,24,2.0,Runner
Rajasthan Royals,18,11,22,3.0,Losing Team in Qualifier2
Sunrisers Hyderabad,17,10,20,4.0,Losing Team in Eliminator
Royal Challengers Bangalore,16,9,18,5.0,
Kings XI Punjab,16,8,16,6.0,
Kolkata Knight Riders,16,6,12,7.0,
Pune Warriors,16,4,8,8.0,
Delhi Daredevils,16,3,6,9.0,

2012

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Kolkata Knight Riders,17,12,24,1.0,Winner
Delhi Daredevils,18,11,22,2.0,Runner
Chennai Super Kings,18,10,20,3.0,Losing Team in Qualifier2
Mumbai Indians,17,10,20,4.0,Losing Team in Eliminator
Kings XI Punjab,16,8,16,5.0,
Royal Challengers Bangalore,15,8,16,6.0,
Rajasthan Royals,16,7,14,7.0,
Deccan Chargers,15,4,8,8.0,
Pune Warriors,16,4,8,9.0,

2011

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Chennai Super Kings,16,11,22,1.0,Winner
Royal Challengers Bangalore,16,10,20,2.0,Runner
Mumbai Indians,16,10,20,3.0,Losing Team in Qualifier2
Kolkata Knight Riders,15,8,16,4.0,Losing Team in Eliminator
Kings XI Punjab,14,7,14,5.0,
Deccan Chargers,14,6,12,6.0,
Rajasthan Royals,13,6,12,7.0,
Kochi Tuskers Kerala,14,6,12,8.0,
Delhi Daredevils,14,4,8,9.0,
Pune Warriors,14,4,8,10.0,

2009/10

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Mumbai Indians,16,11,22,1.0,Winner
Chennai Super Kings,16,9,18,2.0,Runner
Royal Challengers Bangalore,16,8,16,3.0,Losing Team in Qualifier2
Deccan Chargers,16,8,16,4.0,Losing Team in Eliminator
Kolkata Knight Riders,14,7,14,5.0,
Delhi Daredevils,14,7,14,6.0,
Rajasthan Royals,14,6,12,7.0,
Kings XI Punjab,14,4,8,8.0,

2009

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Delhi Daredevils,15,10,20,1.0,Winner
Deccan Chargers,16,9,18,2.0,Runner
Royal Challengers Bangalore,16,9,18,3.0,Losing Team in Qualifier2
Chennai Super Kings,14,8,16,4.0,Losing Team in Eliminator
Kings XI Punjab,14,7,14,5.0,
Mumbai Indians,13,5,10,6.0,
Kolkata Knight Riders,13,3,6,7.0,

2007/08

,Matches Played,Wins,Points,Ranks,Season Position
Team Name,,,,,
Rajasthan Royals,16,13,26,1.0,Winner
Kings XI Punjab,15,10,20,2.0,Runner
Chennai Super Kings,16,9,18,3.0,Losing Team in Qualifier2
Delhi Daredevils,14,7,14,4.0,Losing Team in Eliminator
Mumbai Indians,14,7,14,5.0,
Kolkata Knight Riders,13,6,12,6.0,
Royal Challengers Bangalore,14,4,8,7.0,
Deccan Chargers,14,2,4,8.0,

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [ ]:
# code here

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
# code here